# Generated by Django 3.2 on 2021-04-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0002_explore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Explore',
        ),
    ]
