# Generated by Django 3.2 on 2021-04-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0006_alter_hotelbooking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room',
            field=models.CharField(choices=[(1, '1 person'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people')], default=1, max_length=2),
        ),
    ]
