# Generated by Django 3.2 on 2021-04-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0007_alter_hotelbooking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room',
            field=models.CharField(choices=[('1 person', '1 person'), ('2 people', '2 people'), ('3 people', '3 people'), ('4 people', '4 people'), ('5 people', '5 people')], max_length=64),
        ),
    ]
