# Generated by Django 3.2 on 2021-04-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0010_remove_userhotel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room',
            field=models.CharField(choices=[('1 person', '1 person'), ('2 people', '2 people'), ('3 people', '3 people'), ('4 people', '4 people'), ('5 people', '5 people')], max_length=64),
        ),
        migrations.AlterField(
            model_name='userhotel',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.hotel'),
        ),
        migrations.AlterField(
            model_name='userhotel',
            name='hotel_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.hotelbooking'),
        ),
        migrations.AlterField(
            model_name='userhotel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.user'),
        ),
    ]
