# Generated by Django 3.2 on 2021-04-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0011_auto_20210418_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ManyToManyField(through='travel_agency_app.UserHotel', to='travel_agency_app.Hotel'),
        ),
    ]
