# Generated by Django 3.2 on 2021-04-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0012_auto_20210418_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.hotel'),
        ),
    ]
