# Generated by Django 3.2 on 2021-04-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0013_auto_20210418_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingType', models.CharField(choices=[('Hotel', 'Hotel'), ('Flight', 'Flight')], max_length=64)),
            ],
        ),
    ]
