# Generated by Django 3.2 on 2021-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0014_explore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromCountry', models.CharField(default='Poland', max_length=64)),
                ('fromCity', models.CharField(default='Warsaw', max_length=64)),
                ('toCountry', models.CharField(default='Italy', max_length=64)),
                ('toCity', models.CharField(default='Rome', max_length=64)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('classType', models.CharField(choices=[('economy', 'economy'), ('premium economy', 'premium economy'), ('business', 'business'), ('first class', 'first class')], max_length=64)),
            ],
        ),
    ]
