# Generated by Django 3.2 on 2021-04-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0018_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
