# Generated by Django 3.2 on 2021-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0019_hotel_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='explore',
            name='city',
            field=models.CharField(default='Bali', max_length=64),
        ),
        migrations.AddField(
            model_name='explore',
            name='continent',
            field=models.CharField(default='Asia', max_length=64),
        ),
        migrations.AddField(
            model_name='explore',
            name='country',
            field=models.CharField(default='Indonesia', max_length=64),
        ),
    ]
