# Generated by Django 3.2 on 2021-04-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0023_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='hotel',
        ),
        migrations.AddField(
            model_name='reservations',
            name='hotel_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_agency_app.hotelbooking'),
        ),
    ]
