# Generated by Django 3.2 on 2021-04-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0024_auto_20210423_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='user',
        ),
    ]
