# Generated by Django 3.2 on 2021-04-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0025_remove_reservations_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
