# Generated by Django 3.2 on 2021-05-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0029_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRating',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='travel_agency_app.review')),
            ],
            bases=('travel_agency_app.review',),
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
