# Generated by Django 3.2 on 2021-05-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_app', '0035_review_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore',
            name='city',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='country',
        ),
    ]
